<table border="1" cellpadding="2" class="generalwindow">
	<tr>
		<td class="centertitle">Webmaster管理中心</td>
	</tr>
	<tr>
		<td style="<%=CssBgColor(TableContentBGC)%>">
			<table border="1" cellpadding="0" class="grid" style="text-align:center;">
				<tr style="cursor:pointer">
					<td style="width:17%" onclick="window.location='web_admin.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_admin.asp">管理中心首页</a></td>
					<td style="width:17%" onclick="window.location='web_search.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_search.asp">搜索留言</a></td>
					<td style="width:17%" onclick="window.location='web_searchdec.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_searchdec.asp">搜索置顶公告</a></td>
					<td style="width:17%" onclick="window.location='web_advdel.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_advdel.asp">高级删除</a></td>
					<td style="width:16%" onclick="window.location='web_setbulletin.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_setbulletin.asp">发布系统公告</a></td>
					<td style="width:16%" onclick="window.location='web_chpass.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_chpass.asp">修改密码</a></td>	
				</tr>
				<tr style="cursor:pointer">
					<td style="width:17%" onclick="window.location='web_config.asp?page=1'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_config.asp?page=1">管理中心参数</a></td>
					<td style="width:17%" onclick="window.location='web_ipconfig.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_ipconfig.asp">IP屏蔽策略</a></td>
					<td style="width:17%" onclick="window.location='web_filter.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_filter.asp">内容过滤策略</a></td>
					<td style="width:17%" onclick="window.location='web_floodconfig.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_floodconfig.asp">防灌水策略</a></td>
					<td style="width:16%" onclick="window.location='web_compact.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_compact.asp">压缩数据库</a></td>
					<td style="width:16%" onclick="window.location='web_logoff.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="web_logoff.asp">退出管理</a></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
