<div class="region">
	<h3 class="title">Webmaster管理员控制中心</h3>
	<div class="content flex-box">
		<ul>
			<li><a href="web_admin.asp">管理中心首页</a></li>
			<li><a href="web_search.asp">搜索留言</a></li>
			<li><a href="web_searchdec.asp">搜索置顶公告</a></li>
			<li><a href="web_advdel.asp">高级删除</a></li>
			<li><a href="web_setbulletin.asp">发布系统公告</a></li>
			<li><a href="web_chpass.asp">修改密码</a></li>
			<li><a href="web_config.asp?page=1">管理中心参数</a></li>
			<li><a href="web_ipconfig.asp">IP屏蔽策略</a></li>
			<li><a href="web_filter.asp">内容过滤策略</a></li>
			<li><a href="web_floodconfig.asp">防灌水策略</a></li>
			<li><a href="web_compactdb.asp">压缩数据库</a></li>
			<li><a href="web_logoff.asp">退出管理</a></li>
		</ul>
	</div>
</div>
